Event/MonitoringEvent.php
Event/MonitoringEventInterface.php

As a developer, I would like to handle my events with custom classes and different constructors, implementing MonitoringEventInterface.
By removing the constructor in MonitoringEventInterface

remove constructor in monitoring event interface

---

DependencyInjection/Configuration.php
DependencyInjection/M6WebStatsdPrometheusExtension.php
Doc/configuration.md

We want to be able to prefix every metrics name with the same value.
Add a new top level section named `metrics` with only one child named `prefix`.

Feat: Add a metrics section on top, with a prefix scalar node.

---

Doc/prometheus-grafana.md
composer.json

We missed the m6web/http-kernel-bundle.
Add it to the suggest list, and explain its usage when shown in the doc.

Feat: Add a suggest for `m6web/http-kernel-bundle` and update the doc.

---

DependencyInjection/M6WebStatsdPrometheusExtension.php
Doc/configuration.md
Metric/Metric.php
Metric/MetricHandler.php
Tests/Metric/MetricHandlerTest.php

We noticed some Fatals on prod (couldn't repro on localhost), traced it back to the tagResolver evaluating `request.header.get()`.
Use masterRequest which has less chances of not being instanciated, and more of having the data we're looking for.  
Also, when handling a KernelEvent having the master request, use this request as the stack may be empty.

Use master request on MetricHandler

---

Metric/Metric.php

Given following event:
```yml
- type: 'timer'
name: 'http_request_input_seconds'
param_value: 'getTiming'
tags:
status: 'statusCode'
route: 'routeName'
```
The metric would try to resolve `status` tag by taking the `status` parameter on the event instead of the `statusCode`.

Fix parameter key used on monitoring events tags

---

DependencyInjection/Configuration.php
DependencyInjection/M6WebStatsdPrometheusExtension.php
Doc/configuration.md
Doc/usage.md
Event/KernelExceptionEvent.php
Event/KernelTerminateEvent.php
Listener/EventListener.php
Listener/KernelEventsListener.php
M6WebStatsdPrometheusBundle.php
composer.json

We previously suggested (#9) to use our m6webkernel bundle to provide timings on kernel events but this just add steps and dependencies to configuring this bundle.
- Add a listener and events, just like the custom kernel bundle
- 🎁 investigated and clarified the `Bundle::getContainerExtension()` situation
- 🎁 can cut some code away with `ConfigurableExtension`

Provide built-in events to tag kernel.terminate/exception

---

DependencyInjection/Configuration.php
DependencyInjection/M6WebStatsdPrometheusExtension.php
Resources/views/Collector/statsd_prometheus.html.twig

Template error 
A tree builder without a root node is deprecated since Symfony 4.2 : https://symfony.com/blog/new-in-symfony-4-2-important-deprecations
Fix Template
Fix tree builder

fix datacollector_template

---

Client/UdpClient.php
DependencyInjection/M6WebStatsdPrometheusExtension.php
Metric/Metric.php
Metric/MetricHandler.php
Tests/Metric/MetricHandlerTest.php

Symfony 4.2 seems to have changed the request stack lifecycle since we started to use this bundle.
Now the requestStack is emptied before we use it, so we cannot resolve our special configuration tags anymore:
```
dynamic_one: '@=container.get("my_service_id").getMyValue()' 
another_dynamic_one: '@=request.get("X-Custom-Header")' 
```
By getting the master request from the requestStack  when it is instantiated, and keep its original state until the kernel terminate phase.

fix(request_stack) get master request from request stack to keep its original state

---

Doc/configuration.md
Doc/upgrades/from-1-to-2.md
Doc/usage-and-examples.md
Metric/Metric.php
README.md
Tests/Metric/MetricHandlerTest.php
Tests/Metric/MetricTest.php

We would like to make tags definition works the same anywhere.
This would allow for static value everywhere, and would also make it easier to read and understand.
Sadly, the cost of this change is a light increase in verbosity for the configuration, and the loss of the automatic fall-back from parameters to properties.
However I believe this will avoid unnecessary magic and makes the configuration really explicit.
This is up to discussion, but so far I've these 3 prefixes for none-static values.
* `@=` for container and request resolver, as it was already done.
* `%=` for parameters from the event implementing `MonitoringEventInterface`, returning null if it doesn't or doesn't have this parameter.
* `->` for property accessors on the event, returning null if it is not found.

Prefixes all tags

---

composer.json

Since `symfony/expression-language` is used here:
https://github.com/M6Web/StatsdTagsPrometheusBundle/blob/master/Metric/Metric.php#L64
It should be defined as a mandatory dependency.
Required dependency added to `composer.json`.

Add missing expression language dependency

---

Listener/EventListener.php

When max_queued_metrics option is set, there is a php fatal error because `setMaxNumberOfMetricToQueue()` function does not exists.
Add `setMaxNumberOfMetricToQueue()` function in the evenListener, which is required by setEventListenerAsServiceAndGetServiceId.php when max_queued_metrics option is set.

fix(max_queued_metrics) Allow to set max_queued_metrics parameter

---

Doc/configuration.md

Fix legacy compatibility doc.
Property accessor was not triggered without the `->`
Update documentation

Fix compatibility and legacy behaviour documentation

---

Event/ConsoleMonitoringEvent.php
Metric/Metric.php
Tests/Metric/MetricTest.php

There is some metrics inconsistencies we need to fix.
- When expecting a console memory usage in bytes, we get kilobytes because the value is divided by 1024.
- When using timers, values are divided 1000 by the statsd exporter (see https://github.com/prometheus/statsd_exporter/pull/178/files#diff-557eb2a359922e8de5f18397fed0cd99R423) which expects ms, while prometheus expects seconds. When sending seconds (with `microtime(true)`), values are now incorrect.
- Remove the division by 1024 in the ConsoleMonitoringEvent.
- Multiply timer values by 1000 for timer metrics.

Metrics unit correction

---

DependencyInjection/Configuration.php
Doc/configuration.md
Tests/DependencyInjection/M6WebStatsdPrometheusExtensionTest.php

We have perf and memory issues when a lot of metrics are queued.
I suggests to set the max queued metric value required and add in the doc an advice for the value.

fix(perf): set max queued metric conf required

---

DependencyInjection/M6WebStatsdPrometheusExtension.php
Listener/ConsoleEventsSubscriber.php
Listener/EventListener.php
Metric/MetricHandler.php
Tests/Listener/EventListenerTest.php

In SF 4.4 with the debug disabled, we don't have the request anymore after the kernel terminate event.
Set the request to metric handler on kernel response

fix(tagValues): empty request after kernel terminate

---

Listener/ConsoleEventsSubscriber.php

The wrong event is dispatched on error.
Actually dispatch a ConsoleErrorMonitoringEvent

fix(ConsoleEventsSubscriber): actually fire an error event on error

---

Doc/configuration.md

The exemple in https://github.com/M6Web/StatsdTagsPrometheusBundle/blob/master/Doc/configuration.md#modify-your-configuration-format use events names  instead of events class names

fix: update example in configuration doc

---

DependencyInjection/Configuration.php
DependencyInjection/M6WebStatsdPrometheusExtension.php
Doc/configuration.md
Listener/KernelEventsSubscriber.php
Makefile

- users of this bundle may just want to dispatch some custom events of their choice
=> we should allow users to not dispatch this bundle events, if they don't want to
- add optional configuration keys to be able to disable bundle events dispatching
- fix `make build` (and remove unused `make build-ci`)
=> simple-phpunit must run before phpstan in order to have phpunit vendor file installed

feat(dispatch_events): allow to not dispatch internal events

---

.php_cs
Client/Server.php
Client/UdpClient.php
DependencyInjection/M6WebStatsdPrometheusExtension.php
Event/ConsoleMonitoringEvent.php
Listener/ConsoleListener.php
Metric/Metric.php
Metric/MetricInterface.php
Tests/Metric/MetricTest.php
Tests/Symfony/KernelForTest.php
composer.json

If something wrong happen before the beginning of a command, the `startTime` is `null` and it causes a typing issue:
```
Type error: Argument 2 passed to M6Web\Bundle\StatsdPrometheusBundle\Event\ConsoleMonitoringEvent::createFromConsoleEvent() must be of the type int, null given, called in …/vendor/m6web/statsd-prometheus-bundle/Listener/ConsoleListener.php on line 52  
```
The method `createFromConsoleEvent` should accept `null` value, it's already handled in the code, and `master` branch accept it.
⚠️ First commit contains expected fix, others are here to fix tests 😕 
* It's a fix for `v2.x` branch
* On the road for `v2.0.5`

fix(php): Nullable parameter

---

Client/UdpClient.php
DependencyInjection/Configuration.php
Listener/EventListener.php
Listener/KernelEventsSubscriber.php
Metric/Metric.php
phpstan.neon.dist

KernelEvent::isMasterRequest has been removed in symfony6
Call KernelEvent::isMainRequest if it exists (keep compat with sf 4.4)

fix: symfony6 compatibility

---

Listener/ConsoleEventsSubscriber.php
Listener/EventListener.php
Metric/Metric.php
composer.json

In order to update my project in Symfony 6.2 i need `symfony/contract` 3.x & `psr/container 2.x`.
I also remove `sensiolabs/security-checker` as it is not used anymore.
Some change have been updated after running your php-cs-fixer configuration

Allow symfony/contract 3.* & psr/container 2.*
